### ISSUE TITLE
Implement Department WebAPI Controller, Service, Repository, Models, and Mappers

### ISSUE THREAD

**Issue by raulshma** [raulshma/threeT#21]
### Description:
As a developer, I need to create a WebAPI controller, service, repository, models, and mappers for the Department entity in our GitHub project. This task involves implementing the necessary components to perform CRUD (Create, Read, Update, Delete) operations on the Department entity using the provided code structure. The implementation should follow best practices, utilize the existing generic repository, and include additional functionality to retrieve department managers' name and ID in the GET responses.

### Task Details:

1. Department Entity:
   - Review the provided code for the Department entity (see code snippet below).
   - Ensure that the Department entity includes the necessary properties and relationships.

```csharp
public class Department : BaseEntityWithKey<Guid>
{
    [Required]
    public string Name { get; set; }
    public string Code { get; set; }
    public virtual ICollection<DepartmentManager> DepartmentManagers { get; set; }
}
```

2. Department Repository:
   - Utilize the existing generic repository within the project.
   - Create a Department-specific repository interface and implementation.
   - Implement the necessary methods for CRUD operations on the Department entity using the generic repository.

3. Department Service:
   - Create a Department service that will be used by the controller.
   - Implement methods in the service for handling business logic related to Department entities.
   - Use the Department repository to perform CRUD operations and any additional logic required.

4. Department Controller:
   - Create a Department WebAPI controller that will handle HTTP requests related to the Department entity.
   - Implement REST endpoints for the following operations:
     - Add a department (POST)
     - Get a department by ID (GET)
     - Get all departments (GET)
     - Update a department (PUT)
     - Delete a department (DELETE)
   - Ensure that the GET endpoints include the department manager's name and ID in the response.

5. Models and Mappers:
   - Create necessary models to represent the data required for request/response payloads in the Department controller.
   - Implement mappers to map between the Department entity and the request/response models.

Note: Make sure to adhere to the project structure and coding conventions followed in the project. Follow best practices for separation of concerns, error handling, validation, and authentication if applicable.

### Estimated Effort: 8-10 hours

Acceptance Criteria:
- Department repository interface and implementation are created using the existing generic repository.
- Department service is implemented with methods for CRUD operations and additional logic if needed.
- Department WebAPI controller is created with REST endpoints for adding, retrieving, updating, and deleting departments.
- GET endpoints return department details along with the department manager's name and ID.
- Models are created for request/response payloads and mappers are implemented to map between entity and model.
- Code follows the project structure and coding conventions.
- Unit tests, if applicable, are created to ensure the functionality of the implemented components.

Dependencies:
- Access to the project repository.
- Familiarity with .NET WebAPI, Entity Framework Core, and RESTful API development.
- Knowledge of the project structure and existing generic repository implementation.
- Understanding of coding conventions and best practices for API development.

**Comment by sorvkumr** [comment]
Hi @raulshma.
Code committed for Implementation of CQRS for the Department module. Need to check the Department Manager Username 25151aa .
