### ISSUE TITLE
Implement Designation WebAPI Controller, Service, Repository, Models, and Mappers

### ISSUE THREAD

**Issue by raulshma** [raulshma/threeT#22]
### Description:
As a developer, I need to create a WebAPI controller, service, repository, models, and mappers for the Designation entity in our GitHub project. This task involves implementing the necessary components to perform CRUD (Create, Read, Update, Delete) operations on the Designation entity using the provided code structure. The implementation should follow best practices, utilize the existing generic repository, and ensure adherence to the project structure.

### Task Details:

1. Designation Entity:
   - Review the provided code for the Designation entity (see code snippet below).
   - Ensure that the Designation entity includes the necessary properties and relationships.

```csharp
public class Designation : BaseEntityWithKey<Guid>
{
    [Required]
    public string Name { get; set; }
}
```

2. Designation Repository:
   - Utilize the existing generic repository within the project.
   - Create a Designation-specific repository interface and implementation.
   - Implement the necessary methods for CRUD operations on the Designation entity using the generic repository.

3. Designation Service:
   - Create a Designation service that will be used by the controller.
   - Implement methods in the service for handling business logic related to Designation entities.
   - Use the Designation repository to perform CRUD operations and any additional logic required.

4. Designation Controller:
   - Create a Designation WebAPI controller that will handle HTTP requests related to the Designation entity.
   - Implement REST endpoints for the following operations:
     - Add a designation (POST)
     - Get a designation by ID (GET)
     - Get all designations (GET)
     - Update a designation (PUT)
     - Delete a designation (DELETE)

5. Models and Mappers:
   - Create necessary models to represent the data required for request/response payloads in the Designation controller.
   - Implement mappers to map between the Designation entity and the request/response models.

Note: Ensure that the code follows the project structure and adheres to the coding conventions followed in the project. Consider implementing error handling, validation, and authentication if applicable.

### Estimated Effort: 6-8 hours

Acceptance Criteria:
- Designation repository interface and implementation are created using the existing generic repository.
- Designation service is implemented with methods for CRUD operations and any additional logic if needed.
- Designation WebAPI controller is created with REST endpoints for adding, retrieving, updating, and deleting designations.
- Models are created for request/response payloads, and mappers are implemented to map between entity and model.
- Code follows the project structure and coding conventions.
- Unit tests, if applicable, are created to ensure the functionality of the implemented components.

Dependencies:
- Access to the project repository.
- Familiarity with .NET WebAPI, Entity Framework Core, and RESTful API development.
- Knowledge of the project structure and existing generic repository implementation.
- Understanding of coding conventions and best practices for API development.

**Comment by sorvkumr** [comment]
Review services, mappers, and add checks for add and update designation names. Under commit 6ea9a75.

**Comment by sorvkumr** [comment]
Review services, mappers, and add checks for add and update designation names. Under commit 6ea9a75.

**Comment by raulshma** [comment]
Pending pr

**Comment by sorvkumr** [comment]
Implemented CQRS in Designation module and created merge request under a0a8bc2
