### ISSUE TITLE
Implement Module WebAPI Controller, Service, Repository, Models, and Mappers

### ISSUE THREAD

**Issue by raulshma** [raulshma/threeT#24]
### Description:
As a developer, I need to create a WebAPI controller, service, repository, models, and mappers for the Module entity in our GitHub project. This task involves implementing the necessary components to perform CRUD (Create, Read, Update, Delete) operations on the Module entity using the provided code structure. The implementation should follow best practices, utilize the existing generic repository, and ensure adherence to the project structure.

### Task Details:

1. Module Entity:
   - Review the provided code for the Module entity (see code snippet below).
   - Ensure that the Module entity includes the necessary properties and relationships.

```csharp
public class Module : BaseEntityWithKey<Guid>
{
    [Required]
    public string Name { get; set; }
    [Required]
    public Guid ProjectId { get; set; }
    public virtual Project Project { get; set; }
}
```

2. Module Repository:
   - Utilize the existing generic repository within the project.
   - Create a Module-specific repository interface and implementation.
   - Implement the necessary methods for CRUD operations on the Module entity using the generic repository.

3. Module Service:
   - Create a Module service that will be used by the controller.
   - Implement methods in the service for handling business logic related to Module entities.
   - Use the Module repository to perform CRUD operations and any additional logic required.

4. Module Controller:
   - Create a Module WebAPI controller that will handle HTTP requests related to the Module entity.
   - Implement REST endpoints for the following operations:
     - Add a module to a project (POST)
     - Get all modules for a project by project ID (GET)
     - Get all modules (GET)
     - Update a module (PUT)
     - Update a module projectId (PUT)
     - Delete a module by its ID (DELETE)
     - Delete all modules for a project by project ID (DELETE)

5. Models and Mappers:
   - Create necessary models to represent the data required for request/response payloads in the Module controller.
   - Implement mappers to map between the Module entity and the request/response models.

Note: Ensure that the code follows the project structure and adheres to the coding conventions followed in the project. Consider implementing error handling, validation, and authentication if applicable.

### Estimated Effort: 10-12 hours

Acceptance Criteria:
- Module repository interface and implementation are created using the existing generic repository.
- Module service is implemented with methods for CRUD operations and any additional logic if needed.
- Module WebAPI controller is created with REST endpoints for adding, retrieving, updating, and deleting modules.
- Models are created for request/response payloads, and mappers are implemented to map between entity and model.
- Code follows the project structure and coding conventions.
- Unit tests, if applicable, are created to ensure the functionality of the implemented components.

Dependencies:
- Access to the project repository.
- Familiarity with .NET WebAPI, Entity Framework Core, and RESTful API development.
- Knowledge of the project structure and existing generic repository implementation.
- Understanding of coding conventions and best practices for API development.

**Comment by sorvkumr** [comment]
Add Module  Crud containing project Name 549a5ea.
